[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/mihdicaballero/mento/blob/main/docs/source/examples/beam_summary_ACI_318-19.ipynb)

In [11]:
# Google Colab does not ship mento, so install it when running there.
# Guarded so that building the documentation never shells out to pip.
import sys

if "google.colab" in sys.modules:
    %pip install mento

# Beam summary with ACI 318-19

**Create input dataframe**

This is an example creating the DataFrame directly in the cell but it's easier to load it from an Excel file, as is explained in the User Guide.

In [12]:
from mento import MPa
from mento import BeamSummary, Concrete_ACI_318_19, SteelBar
import pandas as pd

conc = Concrete_ACI_318_19(name="C25", f_c=25 * MPa)
steel = SteelBar(name="ADN 420", f_y=420 * MPa)
data = {
    "Label": ["", "V101", "V102", "V103", "V104"],
    "Comb.": ["", "ELU 1", "ELU 2", "ELU 3", "ELU 4"],
    "b": ["cm", 20, 20, 20, 20],
    "h": ["cm", 50, 50, 50, 50],
    "cc": ["mm", 25, 25, 25, 25],
    "Nx": ["kN", 0, 0, 0, 0],
    "Vz": ["kN", 20, -50, 100, 100],
    "My": ["kNm", 0, -35, 40, 45],
    "ns": ["", 0, 1.0, 1.0, 1.0],
    "dbs": ["mm", 0, 10, 10, 10],
    "sl": ["cm", 0, 20, 20, 20],
    "n1": ["", 2.0, 2, 2.0, 2.0],
    "db1": ["mm", 12, 12, 12, 12],
    "n2": ["", 1.0, 1, 1.0, 0.0],
    "db2": ["mm", 10, 16, 10, 0],
    "n3": ["", 2.0, 0.0, 2.0, 0.0],
    "db3": ["mm", 12, 0, 16, 0],
    "n4": ["", 0, 0.0, 0, 0.0],
    "db4": ["mm", 0, 0, 0, 0],
}
input_df = pd.DataFrame(data)

beam_summary = BeamSummary(concrete=conc, steel_bar=steel, beam_list=input_df)
# Beam summary input data
beam_summary.data

,Label,Comb.,b,h,cc,Nx,Vz,My,ns,dbs,sl,n1,db1,n2,db2,n3,db3,n4,db4
1,V101,ELU 1,20.00 cm,50.00 cm,25.00 mm,0.00 kN,20.00 kN,0.00 kN·m,0,0.00 mm,0.00 cm,2,12.00 mm,1,10.00 mm,2,12.00 mm,0,0.00 mm
2,V102,ELU 2,20.00 cm,50.00 cm,25.00 mm,0.00 kN,-50.00 kN,-35.00 kN·m,1,10.00 mm,20.00 cm,2,12.00 mm,1,16.00 mm,0,0.00 mm,0,0.00 mm
3,V103,ELU 3,20.00 cm,50.00 cm,25.00 mm,0.00 kN,100.00 kN,40.00 kN·m,1,10.00 mm,20.00 cm,2,12.00 mm,1,10.00 mm,2,16.00 mm,0,0.00 mm
4,V104,ELU 4,20.00 cm,50.00 cm,25.00 mm,0.00 kN,100.00 kN,45.00 kN·m,1,10.00 mm,20.00 cm,2,12.00 mm,0,0.00 mm,0,0.00 mm,0,0.00 mm

**Check all beams for shear and flexure**

In [13]:
beam_summary.check()

,Beam,b,h,cc,"As,top","As,bot",Av,"As,req,top","As,req,bot","Av,req",...,"DCRb,top","DCRb,bot",DCRv,Mu,Vu,Nu,"ØMn,top","ØMn,bot",ØVn,Ok?
0,,cm,cm,mm,,,,cm²/m,cm²/m,cm²/m,...,,,,kNm,kN,kN,kNm,kNm,kN,
1,V101,20,50,25,2Ø8,2Ø12+1Ø10 ++ 2Ø12,-,0.0,1.8,0.0,...,0.0,0.0,0.59,0.0,20.0,0.0,17.4,84.1,33.9,✅
2,V102,20,50,25,2Ø12+1Ø16,2Ø8,1eØ10/20,2.8,0.0,0.0,...,0.496,0.0,0.344,-35.0,-50.0,0.0,70.6,17.3,145.2,✅
3,V103,20,50,25,2Ø8,2Ø12+1Ø10 ++ 2Ø16,1eØ10/20,0.0,2.9,3.22,...,0.0,0.372,0.61,40.0,100.0,0.0,17.3,107.4,163.8,✅
4,V104,20,50,25,2Ø8,2Ø12,1eØ10/20,0.0,3.1,2.87,...,0.0,1.175,0.581,45.0,100.0,0.0,17.3,38.3,172.1,❌

**Calculate capacity for all beams for shear and flexure**

In [14]:
beam_summary.check(capacity_check=True)

,Beam,b,h,"As,top","As,bot",Av,"As,top,real","As,bot,real","Av,real","ØMn,top","ØMn,bot",ØVn
0,,cm,cm,,,,cm²,cm²,cm²/m,kNm,kNm,kN
1,V101,20,50,2Ø8,2Ø12+1Ø10 ++ 2Ø12,-,1.0,5.3,0.0,17.4,84.1,33.9
2,V102,20,50,2Ø12+1Ø16,2Ø8,1eØ10/20,4.3,1.0,7.8,70.6,17.3,132.98
3,V103,20,50,2Ø8,2Ø12+1Ø10 ++ 2Ø16,1eØ10/20,1.0,7.1,7.8,17.3,107.4,145.14
4,V104,20,50,2Ø8,2Ø12,1eØ10/20,1.0,2.3,7.8,17.3,38.3,139.33

**Export results to excel**

In [15]:
beam_summary.check().to_excel("Beam summary results.xlsx", index=False)

**See detailed results for shear check**

In [16]:
beam_summary.shear_results()
# See the same results for capacity check, without DCR
# beam_summary.shear_results(capacity_check=True)

,Label,Comb.,"Av,min","Av,req",Av,Vu,Nu,ØVc,ØVs,ØVn,ØVmax,Vu≤ØVmax,Vu≤ØVn,DCR
0,,,cm²/m,cm²/m,cm²/m,kN,kN,kN,kN,kN,kN,,,
1,V101,ELU 1,0.0,0.0,0.0,20.0,0.0,33.9,0.0,33.9,254.36,True,True,0.59
2,V102,ELU 2,0.0,0.0,7.85,-50.0,0.0,31.83,113.32,145.16,258.57,True,True,0.344
3,V103,ELU 3,1.67,3.22,7.85,100.0,0.0,55.71,108.1,163.8,271.99,True,True,0.61
4,V104,ELU 4,1.67,2.87,7.85,100.0,0.0,58.52,113.56,172.08,285.73,True,True,0.581

**See detailed results for flexure check**

In [17]:
beam_summary.flexure_results()
# See the same results for capacity check, without DCR
# beam_summary.flexure_results(capacity_check=True)

,Label,Comb.,Position,"As,min","As,req top","As,req bot",As,Mu,ØMn,Mu≤ØMn,DCR
0,,,,cm²,cm²,cm²,cm²,kNm,kNm,,
1,V101,ELU 1,Bottom,0.0,0.0,1.8,5.31,0.0,84.12,True,0.0
2,V102,ELU 2,Top,3.05,2.76,0.0,4.27,-35.0,70.57,True,0.496
3,V103,ELU 3,Bottom,2.91,0.0,2.91,7.07,40.0,107.41,True,0.372
4,V104,ELU 4,Bottom,3.06,0.0,3.06,2.26,45.0,38.29,False,1.175

**More detailed results**

In [18]:
# See more complete and specific detailed results for shear check for a specific beam index of the summary
beam_summary.nodes[1].shear_results_detailed()

===== BEAM SHEAR DETAILED RESULTS =====
Materials                            Variable     Value  Unit
----------------------------------  ----------  -------  ------
Section Label                                      V102
Concrete strength                       fc           25  MPa
Steel reinforcement yield strength      fy          420  MPa
Concrete density                        wc       2500.0  kg/m³
Normalweight concrete                   λ             1
Safety factor for shear                 Øv         0.75

Geometry                     Variable     Value  Unit
--------------------------  ----------  -------  ------
Section height                  h            50  cm
Section width                   b            20  cm
Clear cover                     cc          2.5  cm
Longitudinal tension rebar      As         4.27  cm²

Design forces                     Variable     Value  Unit
-------------------------------  ----------  -------  ------
Axial, positive for compression      Nu            0  kN
Shear                                Vu          -50  kN

Shear reinforcement strength     Variable     Value  Unit
------------------------------  ----------  -------  ------
Number of stirrups                  ns            1
Stirrup diameter                    db           10  mm
Stirrup spacing                     s            20  cm
Effective height                    d         45.81  cm
Minimum shear reinforcing         Av,min          0  cm²/m
Required shear reinforcing        Av,req          0  cm²/m
Defined shear reinforcing           Av         7.85  cm²/m
Shear rebar strength               ØVs       113.32  kN

Check                          Unit     Value  Min.      Max.  Ok?
----------------------------  ------  -------  ------  ------  -----
Stirrup spacing along length    cm         20            22.9  ✅
Stirrup spacing along width     cm         14           45.81  ✅
Minimum shear reinforcement   cm²/m      7.85  0               ✅
Minimum rebar diameter          mm         10  10              ✅

Shear strength                     Variable     Value  Unit
--------------------------------  ----------  -------  ------
Effective shear area                 Acv       916.12  cm²
Longitudinal reinforcement ratio      ρw      0.00466
Size modification factor              λs         0.84
Axial stress                         σNu          0.0  MPa
Concrete effective shear stress       kc         0.46  MPa
Concrete strength                    ØVc        31.83  kN
Maximum shear strength              ØVmax      258.57  kN
Total shear strength                 ØVn       145.16  kN
Max shear check                                    ✅
Demand Capacity Ratio                DCR         0.34  ✅

In [19]:
# See more complete and specific detailed results for flexure check for a specific beam index of the summary
beam_summary.nodes[2].flexure_results_detailed()

===== BEAM FLEXURE DETAILED RESULTS =====
Materials                            Variable     Value  Unit
----------------------------------  ----------  -------  ------
Section Label                                      V103
Concrete strength                       fc           25  MPa
Steel reinforcement yield strength      fy          420  MPa

Geometry                  Variable     Value  Unit
-----------------------  ----------  -------  ------
Section height               h            50  cm
Section width                b            20  cm
Clear cover                  cc          2.5  cm
Mechanical top cover       cm,top        3.9  cm
Mechanical bottom cover    cm,bot       6.31  cm

Design forces       Variable     Value  Unit
-----------------  ----------  -------  ------
Top max moment       Mu,top          0  kNm
Bottom max moment    Mu,bot         40  kNm

Check                     Unit     Value  Min.      Max.  Ok?
-----------------------  ------  -------  ------  ------  -----
Min/Max As rebar top      cm²       1.01  0        14.69  ✅
Minimum spacing top        mm        114  30              ✅
Min/Max As rebar bottom   cm²       7.07  2.91     13.92  ✅
Minimum spacing bottom     mm         48  25              ✅

Top reinforcement check                    Variable     Value  Unit
----------------------------------------  ----------  -------  ------
First layer bars                            n1+n2         2Ø8
Second layer bars                           n3+n4           -
Effective height                              d          46.1  cm
Depth of equivalent strength block ratio     c/d            0
Minimum rebar reinforcing                   As,min        0.0  cm²
Required rebar reinforcing top            As,req top      0.0  cm²
Required rebar reinforcing bottom         As,req bot     2.91  cm²
Defined rebar reinforcing top                 As         1.01  cm²
Longitudinal reinforcement ratio              ρl      0.00767
Total flexural strength                      ØMn        17.33  kNm
Demand Capacity Ratio                        DCR            0  ✅

Bottom reinforcement check                 Variable       Value  Unit
----------------------------------------  ----------  ---------  ------
First layer bars                            n1+n2     2Ø12+1Ø10
Second layer bars                           n3+n4          2Ø16
Effective height                              d           43.69  cm
Depth of equivalent strength block ratio     c/d         0.0663
Minimum rebar reinforcing                   As,min         2.91  cm²
Required rebar reinforcing top            As,req top        0.0  cm²
Required rebar reinforcing bottom         As,req bot       2.91  cm²
Defined rebar reinforcing bottom              As           7.07  cm²
Longitudinal reinforcement ratio              ρl        0.00809
Total flexural strength                      ØMn         107.41  kNm
Demand Capacity Ratio                        DCR           0.37  ✅

**Export results to Word**

In [20]:
beam_summary.results_detailed_doc(index=1)

✅ Results exported to Beam_Summary_ACI 318-19.docx

**Export results to Excel**

In [ ]:
beam_summary.check().to_excel("Beam_summary_results.xlsx", index=False)