# Shear Wall Summary Design with ACI 318-19

**Create input dataframe without rebar**

When the rebar columns (dbh, sh, dbv, sv) are set to zero, `design()` will automatically select the reinforcement.

In [1]:
from mento import MPa
from mento import ShearWallSummary, Concrete_ACI_318_19, SteelBar
import pandas as pd

conc = Concrete_ACI_318_19(name="H25", f_c=25 * MPa)
steel = SteelBar(name="ADN 420", f_y=420 * MPa)

data = {
    "Level": [
        "",
        "Level 1",
        "Level 1",
        "Level 1",
        "Level 1",
        "Level 2",
        "Level 2",
        "Level 2",
        "Level 2",
        "Level 1",
        "Level 1",
        "Level 1",
        "Level 1",
    ],
    "Label": ["", "M1", "M1", "M1", "M1", "M1", "M1", "M1", "M1", "M2", "M2", "M2", "M2"],
    "Comb.": [
        "",
        "ELU 1",
        "ELU 2",
        "ELU 3",
        "ELU 4",
        "ELU 1",
        "ELU 2",
        "ELU 3",
        "ELU 4",
        "ELU 1",
        "ELU 2",
        "ELU 3",
        "ELU 4",
    ],
    "t": ["cm", 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
    "lw": ["m", 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 2.0, 2.0, 2.0],
    "hw": ["m", 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0],
    "cc": ["mm", 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25],
    "Nx": ["kN", 0, 0, 0, -301, -150, 55.5, 282, -4.5, -240, -163, -17, 332],
    "Vz": ["kN", 264, 138, 123, 152, 32.3, 163, 19, 88.15, 61.2, 29, 47, 21],
    "My": ["kNm", -172, -90, -81, -234, 143, -278, 159, -97, -38, 60, -39, 46.13],
    "dbh": ["mm", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "sh": ["cm", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "dbv": ["mm", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "sv": ["cm", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
}
input_df = pd.DataFrame(data)

wall_summary = ShearWallSummary(concrete=conc, steel_bar=steel, wall_list=input_df)

**Design reinforcement for all walls**

In [2]:
wall_summary.design()

✅ Shear wall design completed for all walls in Summary.

,Level,Label,Comb.,t,lw,hw,cc,Nx,Vz,My,dbh,sh,dbv,sv
0,Level 1,M1,ELU 1,20.00 cm,3.00 m,3.00 m,25.00 mm,0.00 kN,264.00 kN,-172.00 kN·m,10,30,10,30
1,Level 1,M1,ELU 2,20.00 cm,3.00 m,3.00 m,25.00 mm,0.00 kN,138.00 kN,-90.00 kN·m,10,30,10,30
2,Level 1,M1,ELU 3,20.00 cm,3.00 m,3.00 m,25.00 mm,0.00 kN,123.00 kN,-81.00 kN·m,10,30,10,30
3,Level 1,M1,ELU 4,20.00 cm,3.00 m,3.00 m,25.00 mm,-301.00 kN,152.00 kN,-234.00 kN·m,10,30,10,30
4,Level 2,M1,ELU 1,20.00 cm,3.00 m,3.00 m,25.00 mm,-150.00 kN,32.30 kN,143.00 kN·m,10,30,10,30
5,Level 2,M1,ELU 2,20.00 cm,3.00 m,3.00 m,25.00 mm,55.50 kN,163.00 kN,-278.00 kN·m,10,30,10,30
6,Level 2,M1,ELU 3,20.00 cm,3.00 m,3.00 m,25.00 mm,282.00 kN,19.00 kN,159.00 kN·m,10,30,10,30
7,Level 2,M1,ELU 4,20.00 cm,3.00 m,3.00 m,25.00 mm,-4.50 kN,88.15 kN,-97.00 kN·m,10,30,10,30
8,Level 1,M2,ELU 1,20.00 cm,2.00 m,3.00 m,25.00 mm,-240.00 kN,61.20 kN,-38.00 kN·m,10,30,10,30
9,Level 1,M2,ELU 2,20.00 cm,2.00 m,3.00 m,25.00 mm,-163.00 kN,29.00 kN,60.00 kN·m,10,30,10,30
10,Level 1,M2,ELU 3,20.00 cm,2.00 m,3.00 m,25.00 mm,-17.00 kN,47.00 kN,-39.00 kN·m,10,30,10,30
11,Level 1,M2,ELU 4,20.00 cm,2.00 m,3.00 m,25.00 mm,332.00 kN,21.00 kN,46.13 kN·m,10,30,10,30

**Check walls after design**

In [3]:
wall_summary.check()

,Level,Label,t,lw,hw,Horiz.,Vert.,ρt,ρl,"Vu,max",ØVn,DCR,Status
0,,,cm,m,m,,,,,kN,kN,,
1,Level 1,M1,20,3.0,3.0,Ø10/30,Ø10/30,0.00262,0.00262,264.0,1057.3,0.25,✅
2,Level 2,M1,20,3.0,3.0,Ø10/30,Ø10/30,0.00262,0.00262,163.0,1057.3,0.154,✅
3,Level 1,M2,20,2.0,3.0,Ø10/30,Ø10/30,0.00262,0.00262,61.2,704.9,0.087,✅

**Export designed rebar to Excel**

In [4]:
wall_summary.export_design("Shear_wall_design.xlsx")

✅ Shear wall design exported to Shear_wall_design.xlsx

**Import edited design from Excel and re-check**

In [5]:
wall_summary.import_design("Shear_wall_design.xlsx")
wall_summary.check()

✅ Shear wall design imported and summary data updated.

,Level,Label,t,lw,hw,Horiz.,Vert.,ρt,ρl,"Vu,max",ØVn,DCR,Status
0,,,cm,m,m,,,,,kN,kN,,
1,Level 1,M1,20,3.0,3.0,Ø10/30,Ø10/30,0.00262,0.00262,264.0,1057.3,0.25,✅
2,Level 2,M1,20,3.0,3.0,Ø10/30,Ø10/30,0.00262,0.00262,163.0,1057.3,0.154,✅
3,Level 1,M2,20,2.0,3.0,Ø10/30,Ø10/30,0.00262,0.00262,61.2,704.9,0.087,✅

**View detailed shear results**

In [6]:
wall_summary.shear_results()

,Label,Comb.,"ρt,min","ρt,req",ρt,"ρl,min",ρl,Vu,ØVc,ØVs,ØVn,"ØVn,max","Vu≤ØVn,max",Vu≤ØVn,DCR
0,,,,,,,,kN,kN,kN,kN,kN,,,
1,M1,ELU 1,0.0025,0.0025,0.00262,0.0025,0.00262,264.0,562.5,494.8,1057.3,1485.0,True,True,0.25
2,M1,ELU 2,0.0025,0.0025,0.00262,0.0025,0.00262,138.0,562.5,494.8,1057.3,1485.0,True,True,0.131
3,M1,ELU 3,0.0025,0.0025,0.00262,0.0025,0.00262,123.0,562.5,494.8,1057.3,1485.0,True,True,0.116
4,M1,ELU 4,0.0025,0.0025,0.00262,0.0025,0.00262,152.0,562.5,494.8,1057.3,1485.0,True,True,0.144
5,M1,ELU 1,0.0025,0.0025,0.00262,0.0025,0.00262,32.3,562.5,494.8,1057.3,1485.0,True,True,0.031
6,M1,ELU 2,0.0025,0.0025,0.00262,0.0025,0.00262,163.0,562.5,494.8,1057.3,1485.0,True,True,0.154
7,M1,ELU 3,0.0025,0.0025,0.00262,0.0025,0.00262,19.0,562.5,494.8,1057.3,1485.0,True,True,0.018
8,M1,ELU 4,0.0025,0.0025,0.00262,0.0025,0.00262,88.15,562.5,494.8,1057.3,1485.0,True,True,0.083
9,M2,ELU 1,0.0025,0.0025,0.00262,0.0025,0.00262,61.2,375.0,329.87,704.87,990.0,True,True,0.087
10,M2,ELU 2,0.0025,0.0025,0.00262,0.0025,0.00262,29.0,375.0,329.87,704.87,990.0,True,True,0.041
11,M2,ELU 3,0.0025,0.0025,0.00262,0.0025,0.00262,47.0,375.0,329.87,704.87,990.0,True,True,0.067
12,M2,ELU 4,0.0025,0.0025,0.00262,0.0025,0.00262,21.0,375.0,329.87,704.87,990.0,True,True,0.03

**Export detailed results to Word**

In [7]:
wall_summary.results_detailed_doc(index=1)

✅ Results exported to Shear_Wall_Summary_ACI 318-19.docx